/* ==========================================================================
   BANCO DE DADOS OFICIAL DE COLABORADORES SENAI EUCLIDES FACCHINI
   Base atualizada com Área e Setor (Conformidade CIPA / NR-6)
   ========================================================================== */

export const EMPLOYEE_DATABASE = [
  // 1. Docentes e Especialistas por Área / Setor (Planilha Oficial)
  { nif: "01090619", name: "ALEXANDRE APARECIDO DE SOUZA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01095101", name: "ALEXANDRE DE QUEIROZ", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Logística", sector: "Ensino" },
  { nif: "01049580", name: "ALEXANDRE FELIX DE ARAUJO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Metalmecânica", sector: "Ensino" },
  { nif: "01094635", name: "ALINE CASSIANO NAMBA", role: "IFP II - HORISTA", area: "Gestão / Qualidade", sector: "Ensino" },
  { nif: "01108202", name: "ALLAN DA SILVA JUNIOR", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Madeira e Mobiliário", sector: "Ensino" },
  { nif: "01077825", name: "ALLAN EDSON SILVA BENEDUZZI", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Gestão / Logística / Informática", sector: "Ensino" },
  { nif: "01067061", name: "ALMIR LOTITO LIMA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Eletroeletrônica", sector: "Ensino" },
  { nif: "01045838", name: "ANGELICA AFFONSO BASSAN", role: "PROFESSOR CAI", area: "Geral", sector: "Ensino" },
  { nif: "00076749", name: "ANTONIO CARLOS MORETTIN", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Gestão / Logística", sector: "Ensino" },
  { nif: "01090987", name: "APARECIDA ZANGRANDO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL I", area: "Vestuário", sector: "Ensino" },
  { nif: "01089901", name: "AYSLAN OLIVEIRA DA SILVA", role: "ENGENHEIRO ELETRICISTA - NR10", area: "Eletricidade", sector: "Ensino" },
  { nif: "01021529", name: "BRUNO ALVES DE SOUZA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Metalmecânica", sector: "Ensino" },
  { nif: "01074257", name: "CLAUDIA LIBERATO DOS SANTOS", role: "PROFESSOR CAI", area: "Geral", sector: "Ensino" },
  { nif: "01064602", name: "CLEITON CEZAR MONTEIRO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Automotiva", sector: "Ensino" },
  { nif: "01094692", name: "DANIEL DA SILVA MACHADO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01108203", name: "DAYANE CRISTINA BROCCO COSTA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL I", area: "Vestuário", sector: "Ensino" },
  { nif: "01108204", name: "EMERSON HIGOR NOGUEIRA VIEIRA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL - ROBÓTICA", area: "Automação", sector: "Ensino" },
  { nif: "01075102", name: "FLAVIO ERAS BOIAGO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Eletroeletrônica", sector: "Ensino" },
  { nif: "01101672", name: "FLAVIO HENRIQUE BRESCANSIN", role: "IFP II - HORISTA", area: "Soldagem", sector: "Ensino" },
  { nif: "01103465", name: "GIOVANI PEDROSO DE OLIVEIRA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Soldagem", sector: "Ensino" },
  { nif: "01012867", name: "GUSTAVO ANTONIO MARCHIORI", role: "PROFESSOR CAI", area: "Geral", sector: "Ensino" },
  { nif: "01080133", name: "HEBER ROBERTO FERREIRA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01092857", name: "ITAMAR JOSE ZIADI DOS SANTOS", role: "IFP I - HORISTA", area: "Alimentos", sector: "Ensino" },
  { nif: "01092547", name: "JAYME JUNIO ZANCANI VILLELA", role: "IFP I - HORISTA", area: "Alimentos", sector: "Ensino" },
  { nif: "01057208", name: "LEONALDO ZANELATTO", role: "IFP II - HORISTA", area: "Automotiva", sector: "Ensino" },
  { nif: "01108205", name: "LEONARDO - MIRASSOL", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Madeira e Mobiliário", sector: "Ensino" },
  { nif: "01092915", name: "LUCAS GABRIEL DE FREITAS SANTOS", role: "IFP I - HORISTA", area: "Alimentos", sector: "Ensino" },
  { nif: "01108206", name: "MAINAN MARCATO", role: "INSTRUTOR DE SEGURANÇA DO TRABALHO", area: "Saúde e Segurança no Trabalho", sector: "Ensino" },
  { nif: "01052252", name: "MANOELA DOS SANTOS SANCHEZ", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Gestão / Qualidade", sector: "Ensino" },
  { nif: "01089780", name: "MARCELO VINICIUS OLIVEIRA DIONISIO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Soldagem", sector: "Ensino" },
  { nif: "00076929", name: "MARCIO DONIZETE GASPAROTO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Movelaria", sector: "Ensino" },
  { nif: "00076750", name: "MARCIO GARCIA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Movelaria", sector: "Ensino" },
  { nif: "01091146", name: "NATHALIA WATANABE NAMBA", role: "IFP II - HORISTA", area: "Gestão", sector: "Ensino" },
  { nif: "01078483", name: "PAULO ROGERIO DA SILVA CECILIO", role: "IFP II - HORISTA", area: "Gestão", sector: "Ensino" },
  { nif: "01108207", name: "PEDRO FELLIPE CUSTÓDIO MILANI", role: "INSTRUTOR DE FORMACAO PROFISSIONAL I", area: "Eletricidade", sector: "Ensino" },
  { nif: "01081871", name: "RAFAEL FORTI SCALFI", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01081562", name: "RAFAEL MARANGONI PAIXAO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01078489", name: "RAYNNER ANTONIO TOSCHI SILVA", role: "IFP III - HORISTA", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01081852", name: "RENAN JUNIOR DE ALMEIDA SILVA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01068805", name: "ROBERTO DE SOUZA RIBEIRO MORAES", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01068806", name: "ROBERTO DE SOUZA RIBEIRO MORAES JUNIOR", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01108208", name: "ROBERTO SOUZA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL I", area: "Alimentos", sector: "Ensino" },
  { nif: "01108159", name: "RODRIGO CESAR LORENZI", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Madeira e Mobiliário", sector: "Ensino" },
  { nif: "01103298", name: "ROGERIO MONTEIRO DA SILVA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL I", area: "Construção Civil", sector: "Ensino" },
  { nif: "01108209", name: "ROSMARI ZANCANI VILLELA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL I", area: "Alimentos", sector: "Ensino" },
  { nif: "00077149", name: "SERGIO EDUARDO BRUNASSI", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Metalmecânica", sector: "Ensino" },
  { nif: "01108210", name: "SIDNEI MARCIO DO NASCIMENTO", role: "INSTRUTOR DE SEGURANÇA DO TRABALHO", area: "Saúde e Segurança no Trabalho", sector: "Ensino" },
  { nif: "01095031", name: "SILENO MARCOS ARAUJO ORTIN", role: "IFP III - HORISTA", area: "Tecnologia da Informação", sector: "Ensino" },
  { nif: "01108211", name: "VANESSA CRISTINA FERREIRA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL I", area: "Vestuário", sector: "Ensino" },
  { nif: "01108346", name: "VANIA APARECIDA HILARIO DOS SANTOS", role: "INSTRUTOR DE FORMACAO PROFISSIONAL I", area: "Vestuário", sector: "Ensino" },
  { nif: "01084622", name: "WALTER DANILO CETRONE", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Gestão / Logística / Informática", sector: "Ensino" },
  { nif: "01091751", name: "WELLINGTON FERNANDO WAITMAN", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Automotiva", sector: "Ensino" },
  { nif: "01021959", name: "WELLINGTON GONCALVES NORBERTO", role: "INSTRUTOR DE FORMACAO PROFISSIONAL III", area: "Metalmecânica", sector: "Ensino" },
  
  // 2. Setor de Manutenção Industrial
  { nif: "00075636", name: "JOSE ROGERIO DA SILVA", role: "SUPERVISOR DE SERV DE MANUT CONSERVACAO", area: "Manutenção Industrial", sector: "Manutenção Industrial" },
  { nif: "01000380", name: "GEOVANE ROBERTO DA SILVA", role: "OFICIAL DE MANUTENCAO II", area: "Manutenção Industrial", sector: "Manutenção Industrial" },
  { nif: "01099872", name: "ADRIANO HENRIQUE DO CARMO SOARES", role: "OFICIAL DE MANUTENCAO I", area: "Manutenção Industrial", sector: "Manutenção Industrial" },

  // 3. Apoio Pedagógico, Gestão e Qualidade de Vida
  { nif: "01072990", name: "ADRIANA CRISTINA DE JESUS ROSA", role: "ANALISTA DE QUALIDADE DE VIDA", area: "Qualidade de Vida", sector: "Ensino" },
  { nif: "01004817", name: "ELIS VINTURINI DE OLIVEIRA VILA", role: "COORDENADOR ADMINISTRATIVO E FINANCEIRO", area: "Secretaria & Atendimento", sector: "Secretaria & Atendimento" },
  { nif: "00076511", name: "CLAUDEMIR APARECIDO FLORES", role: "COORDENADOR DE ATIV TECNICA E PEDAGOGICA", area: "Coordenação Administrativa", sector: "Coordenação Administrativa" },
  { nif: "00076287", name: "SILVIO RONEI MARCHETTI", role: "COORDENADOR DE RELACION COM A INDUSTRIA", area: "Coordenação Administrativa", sector: "Coordenação Administrativa" },

  // 4. Apoio Técnico e Administrativo Complementar
  { nif: "01016042", name: "ADEMIR TORQUATO", role: "ASSISTENTE DE APOIO TECNICO", area: "Geral", sector: "Ensino" },
  { nif: "01024101", name: "BRUNA REGINA BIANCHINI ROVEDA TEIXEIRA", role: "ASSISTENTE DE APOIO TECNICO", area: "Geral", sector: "Ensino" },
  { nif: "01104522", name: "CELSO ARTHUR HAWTHORNE JUNIOR", role: "ASSISTENTE DE SERVICOS ADMINISTRATIVOS", area: "Secretaria & Atendimento", sector: "Secretaria & Atendimento" },
  { nif: "00076139", name: "CESAR FERRAIOLO BATISTA", role: "DIRETOR DE UNID DE FORMACAO PROFISSIONAL", area: "Coordenação Administrativa", sector: "Coordenação Administrativa" },
  { nif: "01045309", name: "DIEGO SOARES DE OLIVEIRA", role: "ASSISTENTE DE APOIO TECNICO", area: "Geral", sector: "Ensino" },
  { nif: "00076220", name: "ESTELA APARECIDA DA SILVA STURARO", role: "PROFESSOR CAI", area: "Geral", sector: "Ensino" },
  { nif: "01011457", name: "EVERTON LUIZ CERANTULA", role: "TECNICO EM MARCENARIA", area: "Madeira e Mobiliário", sector: "Ensino" },
  { nif: "00073107", name: "FLAVIO ALVES DA SILVA", role: "ORIENTADOR DE PRATICA PROFISSIONAL", area: "Metalmecânica", sector: "Ensino" },
  { nif: "01023853", name: "GUILHERME BARBOSA DE ALMEIDA", role: "AUXILIAR TECNICO", area: "Geral", sector: "Ensino" },
  { nif: "01056784", name: "JERRI FERNANDES DA SILVA", role: "INSTRUTOR DE FORMACAO PROFISSIONAL II", area: "Metalmecânica", sector: "Ensino" },
  { nif: "01099831", name: "JULIA FRANCISCA HORACIO SILVERIO PORTO", role: "AUXILIAR TECNICO DE INCLUSAO - HORISTA", area: "Geral", sector: "Ensino" },
  { nif: "00076293", name: "LUCIANA FLORES", role: "BIBLIOTECARIO", area: "Geral", sector: "Ensino" },
  { nif: "01081390", name: "MARCIA LOPES DE CARVALHO", role: "AUXILIAR DE EXPEDIENTE", area: "Secretaria & Atendimento", sector: "Secretaria & Atendimento" },
  { nif: "01101401", name: "NATALIA GOMES DOS SANTOS", role: "ASSISTENTE DE SERVICOS ADMINISTRATIVOS", area: "Secretaria & Atendimento", sector: "Secretaria & Atendimento" },
  { nif: "01107341", name: "PRISCILA VENANCIO DA SILVA", role: "ASSISTENTE DE SERVICOS ADMINISTRATIVOS", area: "Secretaria & Atendimento", sector: "Secretaria & Atendimento" },
  { nif: "01098549", name: "VICTOR IZAIAS ARANTES", role: "ASSISTENTE DE SERVICOS ADMINISTRATIVOS", area: "Secretaria & Atendimento", sector: "Secretaria & Atendimento" }
];
